PRODUCT_COPY_FILES += \
    vendor/rockchip/rk322x/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/rockchip/rk322x/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/rockchip/rk322x/proprietary/lib/libEGL.so:system/lib/libEGL.so \
    vendor/rockchip/rk322x/proprietary/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/rockchip/rk322x/proprietary/lib/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/rockchip/rk322x/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/rockchip/rk322x/proprietary/lib/libisp_silicomimageisp_api.so:system/lib/libisp_silicomimageisp_api.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/audio.primary.rk30board.so:system/lib/hw/audio.primary.rk30board.so\
    vendor/rockchip/rk322x/proprietary/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/audio.vr_bee_hidraw.default.so:system/lib/hw/audio.vr_bee_hidraw.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/bluetooth.default.so:system/lib/hw/bluetooth.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/bluetooth_rtk.default.so:system/lib/hw/bluetooth_rtk.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/camera.rk30board.so:system/lib/hw/camera.rk30board.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/gralloc.rk30board.so:system/lib/hw/gralloc.rk30board.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/hdmi_cec.rk30board.so:system/lib/hw/hdmi_cec.rk30board.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/hwcomposer.rk30board.so:system/lib/hw/hwcomposer.rk30board.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/lights.rk322x.so:system/lib/hw/lights.rk322x.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/power.rk322x.so:system/lib/hw/power.rk322x.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/sensors.rk30board.so:system/lib/hw/sensors.rk30board.so \
    vendor/rockchip/rk322x/proprietary/lib/hw/tv_input.default.so:system/lib/hw/tv_input.default.so \
    vendor/rockchip/rk322x/proprietary/lib/libgralloc_priv_omx.so:system/lib/libgralloc_priv_omx.so \
    vendor/rockchip/rk322x/proprietary/lib/libOMX_Core.so:system/lib/libOMX_Core.so \
    vendor/rockchip/rk322x/proprietary/lib/libomxvpu_dec.so:system/lib/libomxvpu_dec.so \
    vendor/rockchip/rk322x/proprietary/lib/libomxvpu_enc.so:system/lib/libomxvpu_enc.so \
    vendor/rockchip/rk322x/proprietary/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
    vendor/rockchip/rk322x/proprietary/lib/libjpeghwenc.so:system/lib/libjpeghwenc.so \
    vendor/rockchip/rk322x/proprietary/lib/libiep.so:system/lib/libiep.so \
    vendor/rockchip/rk322x/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/rockchip/rk322x/proprietary/lib/librk_vpuapi.so:system/lib/librk_vpuapi.so \
    vendor/rockchip/rk322x/proprietary/lib/libvpu.so:system/lib/libvpu.so \
    vendor/rockchip/rk322x/proprietary/lib/libpppoe-jni.so:system/lib/libpppoe-jni.so \
    vendor/rockchip/rk322x/proprietary/lib/librp-pppoe.so:system/lib/librp-pppoe.so \
    vendor/rockchip/rk322x/proprietary/lib/libdrm.so:system/lib/libdrm.so \
    vendor/rockchip/rk322x/proprietary/lib/libdrmframework.so:system/lib/libdrmframework.so \
    vendor/rockchip/rk322x/proprietary/lib/libdrmframework_jni.so:system/lib/libdrmframework_jni.so \
    vendor/rockchip/rk322x/proprietary/bin/rksmbd:system/bin/rksmbd \
    vendor/rockchip/rk322x/proprietary/etc/smb.conf:system/etc/smb.conf \
    vendor/rockchip/rk322x/proprietary/etc/smbpasswd:system/etc/smbpasswd \
    vendor/rockchip/rk322x/proprietary/etc/smbusers:system/etc/smbusers \
    vendor/rockchip/rk322x/proprietary/etc/ppp/call-pppd:system/etc/ppp/call-pppd \
    vendor/rockchip/rk322x/proprietary/etc/ppp/ip-down:system/etc/ppp/ip-down \
    vendor/rockchip/rk322x/proprietary/etc/ppp/ip-up:system/etc/ppp/ip-up \
    vendor/rockchip/rk322x/proprietary/etc/ppp/ip-up-vpn:system/etc/ppp/ip-up-vpn \
    vendor/rockchip/rk322x/proprietary/etc/ppp/call-pppd:system/etc/ppp/call-pppd \
    vendor/rockchip/rk322x/proprietary/etc/ppp/call-pppd:system/etc/ppp/call-pppd \
    vendor/rockchip/rk322x/proprietary/etc/ppp/call-pppd:system/etc/ppp/call-pppd \
    vendor/rockchip/rk322x/proprietary/etc/ppp/pppoe.conf:system/etc/ppp/pppoe.conf \
    vendor/rockchip/rk322x/proprietary/etc/ppp/pppoe-secrets:system/etc/ppp/pppoe-secrets \
    vendor/rockchip/rk322x/proprietary/bin/pppoe-connect:system/bin/pppoe-connect \
    vendor/rockchip/rk322x/proprietary/framework/pppoe-service.jar:system/framework/pppoe-service.jar \
    vendor/rockchip/rk322x/proprietary/framework/oat/arm/pppoe-service.odex:system/framework/oat/arm/pppoe-service.odex \
    vendor/rockchip/rk322x/proprietary/bin/pppoe-setup:system/bin/pppoe-setup \
    vendor/rockchip/rk322x/proprietary/bin/pppoe-start:system/bin/pppoe-start \
    vendor/rockchip/rk322x/proprietary/bin/pppoe-status:system/bin/pppoe-status \
    vendor/rockchip/rk322x/proprietary/bin/pppoe-stop:system/bin/pppoe-stop \
    vendor/rockchip/rk322x/proprietary/bin/e2fsck:system/bin/e2fsck \
    vendor/rockchip/rk322x/proprietary/bin/busybox:system/bin/busybox \
    vendor/rockchip/rk322x/proprietary/bin/resize2fs:system/bin/resize2fs \
    vendor/rockchip/rk322x/proprietary/bin/sh:system/bin/sh \
    vendor/rockchip/rk322x/proprietary/lib/libbluetooth_jni.so:system/lib/libbluetooth_jni.so \
    vendor/rockchip/rk322x/proprietary/lib/libext4_utils.so:system/lib/libext4_utils.so \
    vendor/rockchip/rk322x/proprietary/etc/firmware/4343A0.hcd:system/etc/firmware/4343A0.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/awnb108.hcd:system/etc/firmware/awnb108.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm2076b1.hcd:system/etc/firmware/bcm2076b1.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm4339a0.hcd:system/etc/firmware/bcm4339a0.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm4354a1.hcd:system/etc/firmware/bcm4354a1.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm20710a1.hcd:system/etc/firmware/bcm20710a1.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm20710a1_24M.hcd:system/etc/firmware/bcm20710a1_24M.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm20710a1_26M.hcd:system/etc/firmware/bcm20710a1_26M.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm40183b2.hcd:system/etc/firmware/bcm40183b2.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm43241b4.hcd:system/etc/firmware/bcm43241b4.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm43341b0.hcd:system/etc/firmware/bcm43341b0.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm43438a0.hcd:system/etc/firmware/bcm43438a0.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/bcm43438a1.hcd:system/etc/firmware/bcm43438a1.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/BCM4330B1.hcd:system/etc/firmware/BCM4330B1.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/BCM4343B0.hcd:system/etc/firmware/BCM4343B0.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/BCM4345C0.hcd:system/etc/firmware/BCM4345C0.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/BCM4354A2.hcd:system/etc/firmware/BCM4354A2.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/BCM4356A2.hcd:system/etc/firmware/BCM4356A2.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_awnb108.bin:system/etc/firmware/fw_awnb108.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_awnb108_ap.bin:system/etc/firmware/fw_awnb108_ap.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4330.bin:system/etc/firmware/fw_bcm4330.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4330_apsta.bin:system/etc/firmware/fw_bcm4330_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4334b1_ag.bin:system/etc/firmware/fw_bcm4334b1_ag.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4334b1_ag_apsta.bin:system/etc/firmware/fw_bcm4334b1_ag_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4334b1_ag_p2p.bin:system/etc/firmware/fw_bcm4334b1_ag_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4339a0_ag.bin:system/etc/firmware/fw_bcm4339a0_ag.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4339a0_ag_apsta.bin:system/etc/firmware/fw_bcm4339a0_ag_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4339a0_ag_p2p.bin:system/etc/firmware/fw_bcm4339a0_ag_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4354a1_ag.bin:system/etc/firmware/fw_bcm4354a1_ag.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4354a1_ag_apsta.bin:system/etc/firmware/fw_bcm4354a1_ag_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4354a1_ag_p2p.bin:system/etc/firmware/fw_bcm4354a1_ag_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4356a2_ag.bin:system/etc/firmware/fw_bcm4356a2_ag.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4356a2_ag_apsta.bin:system/etc/firmware/fw_bcm4356a2_ag_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm4356a2_ag_p2p.bin:system/etc/firmware/fw_bcm4356a2_ag_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm40181a2.bin:system/etc/firmware/fw_bcm40181a2.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm40181a2_apsta.bin:system/etc/firmware/fw_bcm40181a2_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm40183b2.bin:system/etc/firmware/fw_bcm40183b2.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm40183b2_ag.bin:system/etc/firmware/fw_bcm40183b2_ag.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm40183b2_ag_apsta.bin:system/etc/firmware/fw_bcm40183b2_ag_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm40183b2_ag_p2p.bin:system/etc/firmware/fw_bcm40183b2_ag_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm40183b2_apsta.bin:system/etc/firmware/fw_bcm40183b2_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm40183b2_p2p.bin:system/etc/firmware/fw_bcm40183b2_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43241b4_ag.bin:system/etc/firmware/fw_bcm43241b4_ag.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43241b4_ag_apsta.bin:system/etc/firmware/fw_bcm43241b4_ag_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43241b4_ag_p2p.bin:system/etc/firmware/fw_bcm43241b4_ag_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43341b0_ag.bin:system/etc/firmware/fw_bcm43341b0_ag.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43341b0_ag_apsta.bin:system/etc/firmware/fw_bcm43341b0_ag_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43341b0_ag_p2p.bin:system/etc/firmware/fw_bcm43341b0_ag_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43436b0.bin:system/etc/firmware/fw_bcm43436b0.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43436b0_apsta.bin:system/etc/firmware/fw_bcm43436b0_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43438a0.bin:system/etc/firmware/fw_bcm43438a0.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43438a0_apsta.bin:system/etc/firmware/fw_bcm43438a0_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43438a0_p2p.bin:system/etc/firmware/fw_bcm43438a0_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43438a1.bin:system/etc/firmware/fw_bcm43438a1.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43438a1_apsta.bin:system/etc/firmware/fw_bcm43438a1_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43438a1_p2p.bin:system/etc/firmware/fw_bcm43438a1_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43455c0_ag.bin:system/etc/firmware/fw_bcm43455c0_ag.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43455c0_ag_apsta.bin:system/etc/firmware/fw_bcm43455c0_ag_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_bcm43455c0_ag_p2p.bin:system/etc/firmware/fw_bcm43455c0_ag_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK901.bin:system/etc/firmware/fw_RK901.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK901a0.bin:system/etc/firmware/fw_RK901a0.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK901a0_apsta.bin:system/etc/firmware/fw_RK901a0_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK901a2.bin:system/etc/firmware/fw_RK901a2.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK901a2_apsta.bin:system/etc/firmware/fw_RK901a2_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK901a2_p2p.bin:system/etc/firmware/fw_RK901a2_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK903.bin:system/etc/firmware/fw_RK903.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK903_ag.bin:system/etc/firmware/fw_RK903_ag.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK903_ag_apsta.bin:system/etc/firmware/fw_RK903_ag_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK903_ag_p2p.bin:system/etc/firmware/fw_RK903_ag_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK903b2.bin:system/etc/firmware/fw_RK903b2.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK903b2_apsta.bin:system/etc/firmware/fw_RK903b2_apsta.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK903b2_p2p.bin:system/etc/firmware/fw_RK903b2_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/fw_RK903_p2p.bin:system/etc/firmware/fw_RK903_p2p.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nh660.hcd:system/etc/firmware/nh660.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_4330.txt:system/etc/firmware/nvram_4330.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_4330_oob.txt:system/etc/firmware/nvram_4330_oob.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_ap62x2.txt:system/etc/firmware/nvram_ap62x2.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_ap6212.txt:system/etc/firmware/nvram_ap6212.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_ap6212a.txt:system/etc/firmware/nvram_ap6212a.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_ap6233f.txt:system/etc/firmware/nvram_ap6233f.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_ap6236.txt:system/etc/firmware/nvram_ap6236.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_ap6255.txt:system/etc/firmware/nvram_ap6255.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_ap6354.txt:system/etc/firmware/nvram_ap6354.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_ap6356.txt:system/etc/firmware/nvram_ap6356.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_ap6356s.txt:system/etc/firmware/nvram_ap6356s.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_ap6452.txt:system/etc/firmware/nvram_ap6452.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_AP6181.txt:system/etc/firmware/nvram_AP6181.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_AP6210.txt:system/etc/firmware/nvram_AP6210.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_AP6210_24M.txt:system/etc/firmware/nvram_AP6210_24M.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_AP6234.txt:system/etc/firmware/nvram_AP6234.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_AP6330.txt:system/etc/firmware/nvram_AP6330.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_AP6335.txt:system/etc/firmware/nvram_AP6335.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_AP6441.txt:system/etc/firmware/nvram_AP6441.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_AP6476.txt:system/etc/firmware/nvram_AP6476.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_AP6493.txt:system/etc/firmware/nvram_AP6493.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_awnb108.txt:system/etc/firmware/nvram_awnb108.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_B23.txt:system/etc/firmware/nvram_B23.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_GB86302I.txt:system/etc/firmware/nvram_GB86302I.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_RK901.txt:system/etc/firmware/nvram_RK901.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_RK903.cal:system/etc/firmware/nvram_RK903.cal \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_RK903.txt:system/etc/firmware/nvram_RK903.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_RK903_26M.cal:system/etc/firmware/nvram_RK903_26M.cal \
    vendor/rockchip/rk322x/proprietary/etc/firmware/nvram_WL211.txt:system/etc/firmware/nvram_WL211.txt \
    vendor/rockchip/rk322x/proprietary/etc/firmware/otp.bin.z77:system/etc/firmware/otp.bin.z77 \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rk903.hcd:system/etc/firmware/rk903.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rk903_26M.hcd:system/etc/firmware/rk903_26M.hcd \
    vendor/rockchip/rk322x/proprietary/etc/firmware/RT2870AP.dat:system/etc/firmware/RT2870AP.dat \
    vendor/rockchip/rk322x/proprietary/etc/firmware/RT2870APCard.dat:system/etc/firmware/RT2870APCard.dat \
    vendor/rockchip/rk322x/proprietary/etc/firmware/RT2870STA.dat:system/etc/firmware/RT2870STA.dat \
    vendor/rockchip/rk322x/proprietary/etc/firmware/RT2870STACard.dat:system/etc/firmware/RT2870STACard.dat \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8703bs_config:system/etc/firmware/rtl8703bs_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8703bs_fw:system/etc/firmware/rtl8703bs_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723b_config:system/etc/firmware/rtl8723b_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723b_fw:system/etc/firmware/rtl8723b_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723bs_config:system/etc/firmware/rtl8723bs_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723bs_fw:system/etc/firmware/rtl8723bs_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723bs_VQ0_config:system/etc/firmware/rtl8723bs_VQ0_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723bs_VQ0_fw:system/etc/firmware/rtl8723bs_VQ0_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723bu_config:system/etc/firmware/rtl8723bu_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723cs_xx_config:system/etc/firmware/rtl8723cs_xx_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723cs_xx_fw:system/etc/firmware/rtl8723cs_xx_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723d_config:system/etc/firmware/rtl8723d_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723d_fw:system/etc/firmware/rtl8723d_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723ds_config:system/etc/firmware/rtl8723ds_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8723ds_fw:system/etc/firmware/rtl8723ds_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8761a_config:system/etc/firmware/rtl8761a_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8761a_fw:system/etc/firmware/rtl8761a_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8761at_config:system/etc/firmware/rtl8761at_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8761at_fw:system/etc/firmware/rtl8761at_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8761au8192ee_fw:system/etc/firmware/rtl8761au8192ee_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8761au8812ae_fw:system/etc/firmware/rtl8761au8812ae_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8761au_fw:system/etc/firmware/rtl8761au_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8761aw8192eu_config:system/etc/firmware/rtl8761aw8192eu_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8761aw8192eu_fw:system/etc/firmware/rtl8761aw8192eu_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8821a_config:system/etc/firmware/rtl8821a_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8821a_fw:system/etc/firmware/rtl8821a_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8821as_config:system/etc/firmware/rtl8821as_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8821as_fw:system/etc/firmware/rtl8821as_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8821c_config:system/etc/firmware/rtl8821c_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8821c_fw:system/etc/firmware/rtl8821c_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8821cs_config:system/etc/firmware/rtl8821cs_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8821cs_fw:system/etc/firmware/rtl8821cs_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8822b_config:system/etc/firmware/rtl8822b_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8822b_fw:system/etc/firmware/rtl8822b_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8822bs_config:system/etc/firmware/rtl8822bs_config \
    vendor/rockchip/rk322x/proprietary/etc/firmware/rtl8822bs_fw:system/etc/firmware/rtl8822bs_fw \
    vendor/rockchip/rk322x/proprietary/etc/firmware/ssv6051-sw.bin:system/etc/firmware/ssv6051-sw.bin \
    vendor/rockchip/rk322x/proprietary/etc/firmware/ssv6051-wifi.cfg:system/etc/firmware/ssv6051-wifi.cfg \
    vendor/rockchip/rk322x/proprietary/etc/firmware/wifi_efuse_8189e.map:system/etc/firmware/wifi_efuse_8189e.map \
    vendor/rockchip/rk322x/proprietary/etc/firmware/wifi_efuse_8723bs-vq0.map:system/etc/firmware/wifi_efuse_8723bs-vq0.map \
    vendor/rockchip/rk322x/proprietary/etc/firmware/wifi_efuse_8723ds.map:system/etc/firmware/wifi_efuse_8723ds.map \
    vendor/rockchip/rk322x/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/rockchip/rk322x/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/rockchip/rk322x/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/rockchip/rk322x/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/rockchip/rk322x/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/rockchip/rk322x/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/rockchip/rk322x/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd \
    vendor/rockchip/rk322x/proprietary/lib/modules/8188eu.ko:system/lib/modules/8188eu.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/8188fu.ko:system/lib/modules/8188fu.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/8189es.ko:system/lib/modules/8189es.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/8723bs.ko:system/lib/modules/8723bs.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/8723cs.ko:system/lib/modules/8723cs.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/8822bs.ko:system/lib/modules/8822bs.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/8822bu.ko:system/lib/modules/8822bu.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/bcmdhd.ko:system/lib/modules/bcmdhd.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/esp8089.ko:system/lib/modules/esp8089.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/readme.txt:system/lib/modules/readme.txt \
    vendor/rockchip/rk322x/proprietary/lib/modules/rk29-ipp.ko:system/lib/modules/rk29-ipp.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/rk29-ipp.ko.3.0.36+:system/lib/modules/rk29-ipp.ko.3.0.36+ \
    vendor/rockchip/rk322x/proprietary/lib/modules/rk29-ipp.ko.3.0.101+:system/lib/modules/rk29-ipp.ko.3.0.101+ \
    vendor/rockchip/rk322x/proprietary/lib/modules/ssv6051.ko:system/lib/modules/ssv6051.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/vcodec_service.ko:system/lib/modules/vcodec_service.ko \
    vendor/rockchip/rk322x/proprietary/lib/modules/wlan.ko:system/lib/modules/wlan.ko \
    vendor/rockchip/rk322x/proprietary/lib/rtkbt/3dd_service.so:system/lib/rtkbt/3dd_service.so \
    vendor/rockchip/rk322x/proprietary/lib/rtkbt/autopair.so:system/lib/rtkbt/autopair.so \
    vendor/rockchip/rk322x/proprietary/lib/rtkbt/autopair_huawei.so:system/lib/rtkbt/autopair_huawei.so \
    vendor/rockchip/rk322x/proprietary/lib/rtkbt/autopair_stack.so:system/lib/rtkbt/autopair_stack.so \
    vendor/rockchip/rk322x/proprietary/lib/rtkbt/heartbeat.so:system/lib/rtkbt/heartbeat.so \
    vendor/rockchip/rk322x/proprietary/lib/rtkbt/vr_bee1_hidraw.so:system/lib/rtkbt/vr_bee1_hidraw.so \
    vendor/rockchip/rk322x/proprietary/lib/rtkbt/vr_bee2_hidraw.so:system/lib/rtkbt/vr_bee2_hidraw.so \
    vendor/rockchip/rk322x/proprietary/lib/soundfx/libaudiopreprocessing.so:system/lib/soundfx/libaudiopreprocessing.so \
    vendor/rockchip/rk322x/proprietary/lib/soundfx/libbundlewrapper.so:system/lib/soundfx/libbundlewrapper.so \
    vendor/rockchip/rk322x/proprietary/lib/soundfx/libdownmix.so:system/lib/soundfx/libdownmix.so \
    vendor/rockchip/rk322x/proprietary/lib/soundfx/libeffectproxy.so:system/lib/soundfx/libeffectproxy.so \
    vendor/rockchip/rk322x/proprietary/lib/soundfx/libldnhncr.so:system/lib/soundfx/libldnhncr.so \
    vendor/rockchip/rk322x/proprietary/lib/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
    vendor/rockchip/rk322x/proprietary/lib/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \
    vendor/rockchip/rk322x/proprietary/etc/permissions/android.hardware.hdmi.cec.xml:system/etc/permissions/android.hardware.hdmi.cec.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/android.software.app_widgets.xml:system/etc/permissions/android.software.app_widgets.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/android.software.webview.xml:system/etc/permissions/android.software.webview.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/box_core_hardware.xml:system/etc/permissions/box_core_hardware.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/com.android.location.provider.xml:system/etc/permissions/com.android.location.provider.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/com.android.media.remotedisplay.xml:system/etc/permissions/com.android.media.remotedisplay.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/com.android.media.tv.remoteprovider.xml:system/etc/permissions/com.android.media.tv.remoteprovider.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/com.android.mediadrm.signer.xml:system/etc/permissions/com.android.mediadrm.signer.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/features.xml:system/etc/permissions/features.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/platform.xml:system/etc/permissions/platform.xml \
    vendor/rockchip/rk322x/proprietary/etc/permissions/tv_core_hardware.xml:system/etc/permissions/tv_core_hardware.xml \
    vendor/rockchip/rk322x/proprietary/lib/libRkOMX_Resourcemanager.so:system/lib/libRkOMX_Resourcemanager.so \
    vendor/rockchip/rk322x/proprietary/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
    vendor/rockchip/rk322x/proprietary/lib/libapedec.so:system/lib/libapedec.so \
    vendor/rockchip/rk322x/proprietary/lib/libbt-vendor_uart.so:system/lib/libbt-vendor_uart.so \
    vendor/rockchip/rk322x/proprietary/lib/libbt-vendor_usb.so:system/lib/libbt-vendor_usb.so \
    vendor/rockchip/rk322x/proprietary/lib/libcameragl.so:system/lib/libcameragl.so \
    vendor/rockchip/rk322x/proprietary/lib/libcam_facedetection.so:system/lib/libcam_facedetection.so \
    vendor/rockchip/rk322x/proprietary/lib/libcsiconv.so:system/lib/libcsiconv.so \
    vendor/rockchip/rk322x/proprietary/lib/libffmpeg.so:system/lib/libffmpeg.so \
    vendor/rockchip/rk322x/proprietary/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/rockchip/rk322x/proprietary/lib/libhevcdec.so:system/lib/libhevcdec.so \
    vendor/rockchip/rk322x/proprietary/lib/libiconv.so:system/lib/libiconv.so \
    vendor/rockchip/rk322x/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/rockchip/rk322x/proprietary/lib/libjesancache.so:system/lib/libjesancache.so \
    vendor/rockchip/rk322x/proprietary/lib/libMFDenoise.so:system/lib/libMFDenoise.so \
    vendor/rockchip/rk322x/proprietary/lib/libmpp.so:system/lib/libmpp.so \
    vendor/rockchip/rk322x/proprietary/lib/libmultiwindow.so:system/lib/libmultiwindow.so \
    vendor/rockchip/rk322x/proprietary/lib/libopencv_java3.so:system/lib/libopencv_java3.so \
    vendor/rockchip/rk322x/proprietary/lib/librk_audio.so:system/lib/librk_audio.so \
    vendor/rockchip/rk322x/proprietary/lib/librkbm.so:system/lib/librkbm.so \
    vendor/rockchip/rk322x/proprietary/lib/librk_demux.so:system/lib/librk_demux.so \
    vendor/rockchip/rk322x/proprietary/lib/librk_hevcdec.so:system/lib/librk_hevcdec.so \
    vendor/rockchip/rk322x/proprietary/lib/librkswscale.so:system/lib/librkswscale.so \
    vendor/rockchip/rk322x/proprietary/lib/librkwmapro.so:system/lib/librkwmapro.so \
    vendor/rockchip/rk322x/proprietary/lib/librockchip_pip_jni.so:system/lib/librockchip_pip_jni.so \
    vendor/rockchip/rk322x/proprietary/lib/librockchip_update_jni.so:system/lib/librockchip_update_jni.so \
    vendor/rockchip/rk322x/proprietary/lib/librockcv_java.so:system/lib/librockcv_java.so \
    vendor/rockchip/rk322x/proprietary/lib/libsupol.so:system/lib/libsupol.so \
    vendor/rockchip/rk322x/proprietary/lib/libtvsettings-jni.so:system/lib/libtvsettings-jni.so


PRODUCT_PACKAGES += \
    libjpeghwdec \
    librkffplayer \
    librga
